### PR TITLE
Modifications to office world navgraph

### PR DESCRIPTION
**Pull request by Yadunund**
* Connected bottom nodes in the graph
* Removed `cubicle_1` and `cubicle_2`
* Replaced `station_1` with `tinyRobot1_charger`. Moved `tinyRobot2_charger` to below `lounge`
* Updated dashboard config files

### CODE REVIEW

**Comment by Yadunund** [comment]
image

**Comment by mxgrey** [comment]
Have you tested moving a robot through the bottom left corner? I believe it may crash into the small filing cabinet that's sticking into the lane.

**Comment by Yadunund** [comment]
Good catch! Have removed the model.
https://user-images.githubusercontent.com/13482049/108346067-f3810580-7219-11eb-8b2d-90fe076ca63f.mp4

**Review by mxgrey — APPROVED** [review]
Thanks, this should allow for much more interesting traffic management scenarios :+1:

**Pull request merged**
