### PR TITLE
Feature/doors

### PR DESCRIPTION
**Pull request by aaronchongth**
* added 2 sets of `double_hinged` doors at the positions mentioned in the proposal
* added an extra `MiR100` to the looping scenario that will go through a door when launched

### CODE REVIEW

**Comment by aaronchongth** [comment]
yup! that can certainly be done, our door thickness is currently hardcoded, so it should be trivial to add more door links and figure out their geometry. I can add that feature on `building_map_tools` and revisit this PR again after that has been implemented and merged

**Comment by Yadunund** [comment]
@codebot 's suggestion solves the issue in an efficient manner. 

image

**Comment by aaronchongth** [comment]
ohh I misread, hmm, I tried it out and feel that @codebot suggestion here https://github.com/osrf/traffic_editor/issues/101 might be more elegant.

Screenshot from 2020-03-23 14-30-09

This way we won't have super close vertices in the map, or that all the maps need to be updated to have extra wall segments. Let me know what you think, @Yadunund

**Comment by aaronchongth** [comment]
After some tweaking around, I have come to realize @Yadunund's implementation is the most straightforward and useful for now. 

image

I have added some additional lanes on the west side of the map, and have the third `MiR100` robot looping between `west_koi_pond` and `junction_n01`
image

thanks for all the advice!

**Pull request merged**
