### PR TITLE
Add single level crowdsim demo for clinic and office

### PR DESCRIPTION
**Pull request by tianenchong**
This adds office and airport_terminal demo with crowd simulation, i.e. you get to see people walking in the office doing sorts of things while tinyrobot fleets are running around.

Added `building_crowdsim` build task for just office and airport_terminal world in `CMakeLists.txt` in `rmf_demo_maps`.
Added `MaleVisitorPhone` Model to `rmf_demo_assets`.
Added launch file named `office_crowd.launch.xml` and `airport_terminal_crowd.launch.xml` alongside with other demo launch files
Modified `office.building.yaml` and `airport_terminal.building.yaml` to Fred's version to include parameter key: `human_goal_set_name`
Modified `airport_terminal.building.yaml` to include `crowd_sim` and remove `_placeholder` to match `agents_name` under `crowd_sim`

### CODE REVIEW

**Comment by luca-della-vedova** [comment]
We are trying to avoid committing binaries to the repo since they make its size increase quite a lot (we had a few assets in the past and because git clones the whole history now the repo is quite large).
Would it be possible to not include the model and have it downloaded by the tools from Fuel (i.e. `pit_crew`) at map building time?

**Comment by tianenchong** [comment]
I think it is possible. I see if I can make changes to `CMakeLists.txt` in `rmf_demo_assets`.

**Comment by luca-della-vedova** [comment]
I'm not a particularly big fan of this approach since it requires manual edits to the CMakeLists for every single model.
We have a tool for automatically downloading the models needed in simulation, [pit_crew](https://github.com/osrf/traffic_editor/tree/master/building_map_tools/pit_crew), which might be a better fit for the purpose (and wouldn't require changing the CMakeLists for every model that we add).

Iirc the [model_downloader](https://github.com/osrf/traffic_editor/blob/master/building_map_tools/model_downloader/model_downloader.py) is also integrated with the map building process so it is ran at building time.

**Comment by tianenchong** [comment]
superseded by feature/add multilevel crowdsim pr

**Pull request closed without merging**
