### PR TITLE
Changing demos package name to rmf_demos

### PR DESCRIPTION
**Pull request by marcoag**
A more concrete name is needed so this package can be identified under the ROS ecosystem.

### CODE REVIEW

**Comment by Yadunund** [comment]
Looks good. Could you also update the `.github/workflows/build.yaml` file with the new package name?

**Comment by marcoag** [comment]
Sure

**Comment by Yadunund** [comment]
@marcoag can this be merged?

**Comment by marcoag** [comment]
will come back to this when the repo split happens.

**Pull request closed without merging**
