### PR TITLE
Add hotel doors & full hotel

### PR DESCRIPTION
**Pull request by MakinoharaShouko**
I just finished adding doors to the hotel demo. The robot traffic is working fine with doors, though memory usage of gazebo rises.

Additionally, I also put the full hotel demo into the repo along with the third robot model I used. I changed the robot's name to _CafeRobot_. Unfortunately, I cannot test the full hotel running due to high memory cost, but it should work if the user has large enough memory. The `README` is updated as well to include this change.

### CODE REVIEW

**Comment by Yadunund** [comment]
Could you mention how the new robot model was obtained? Did you create it yourself? If not, where did you obtain it and what license does it come with?

**Comment by MakinoharaShouko** [comment]
It's [X2 Config 5](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/X2%20Config%205) from ignition fuel but I removed the sensors and the lights. If it does not work I will just replace it with another robot currently in the assets.

**Comment by Yadunund** [comment]
@aaronchongth do you think we should add another robot model to `rmf_demo_assets`? I'm in favor of no and instead using the HospitalRobot model that is already included.

**Comment by aaronchongth** [comment]
Hey @MakinoharaShouko! It is generally a bad idea to commit binaries into repositories, as it will stay in the git history forever, thus only ever increasing the size of the repository without any chance of cleaning it up. This is the reason why cloning `rmf_demos` takes a large amount of time at the moment. This repository started out small for private demos but have grown out of that scope.

I would agree with @Yadunund that we should not add another robot. We should either only rely on `pit_crew` to download and configure models from `Fuel`, or use existing robots that are already in the repository. `HospitalRobot` is a good candidate, the only caveat is that the current `slotcar` plugin is not yet able to toggle off `reversible`, which will cause the robot to move around backwards.

**Comment by MakinoharaShouko** [comment]
I just removed the robot and replaced it with hospitalRobot in the map.

**Review by Yadunund — APPROVED** [review]
Thanks for expanding the hotel map!

**Pull request merged**
